### ISSUE TITLE
Add bb link wrapping bower link

### ISSUE THREAD

**Issue by operatino** [Backbase/bb-cli#10]
`bower link` (same as `npm link`) http://bower.io/docs/api/#link allows to easily install local hosted dependencies instead of remote endpoints. This is very usefull for new component development process, or for testing forked components changes.

Differenct between `bb link` and `bb deploy` is that first one will be only creating symlink, insted of copying all the files to deploy target. But this will work only with right Jetty server configuration, as it by default ignores symlink folders.

**Comment by igord** [comment]
Closing as it becomes irrelevant with 5.6 structure and import-item command.

**Comment by operatino** [comment]
5.6 still allows to keep file-system hosted components, my idea was to keep this flexibility.

**Comment by GuilhermeMedeiros** [comment]
Then we should look at this @igord. Having a link it would be better than zipping it every time indeed.
