### ISSUE TITLE
Development environment doesn't works generating lp56-widget

### ISSUE THREAD

**Issue by tcorral** [Backbase/bb-cli#102]
There are some problems with the index.dev.html that should be used to develop the widget in an isolated environment.

I think that the best solution should share the same template that Launchpad team is using for their development, but while it's not possible I will create a pull-request to fix it.

**Comment by mistermark** [comment]
Or do we want to separate the Launchpad structured widgets/containers by namespace and have more generic structured items with the default namespace?

If the Launchpad structure of the widgets is something that's becoming more the standard we can generalise on this.

**Comment by igord** [comment]
nightly version is downloading template from bitbucket which is synced with stash
