### ISSUE TITLE
Add command labels to Github issues

### ISSUE THREAD

**Issue by mistermark** [Backbase/bb-cli#105]
When going through the issues on Github it's sometimes unclear what command the issue is related to.

I would suggest to create labels related to the commands that exist in the `bb` command so it's easier to filter through the issues based on the command it's related to.

More generic issues that are not directly related to any command can be filed under a label called "general".

@craigwalkeruk @igord: Would love to hear your idea about this.

**Comment by sorohan** [comment]
I approve of this message. @igord can implement :-)

FYI Mark we are looking at restructuring bb-cli into separate commands so they can be maintained easier. We'll continue to aggregate them into a single bb-cli though.

Eg. I will create a "bb-theme build" sub-command which you could install individually - but it will also be able to be called through the bb-cli as "bb theme build".

**Comment by craigwalkeruk** [comment]
@mistermark - Good Idea.. regarding labels..

@sorohan - Please can we put these sub command repo also on github?

**Comment by sorohan** [comment]
@craigwalkeruk I think so yeah. We were going to start them on stash/private first until they're stable.
