### ISSUE TITLE
bb#0.2.3 - Generate Module is not taking template from stash

### ISSUE THREAD

**Issue by KarunaL** [Backbase/bb-cli#112]
bb#0.2.2 is having template in local but 0.2.3 is trying to do git clone from stash.backbase.com.

So when i try to generate new module it gives me error as "Error trying to update template from stash 1".

How to resolve this please ?

**Comment by craigwalkeruk** [comment]
Good afternoon, The correct template the CLI should use is here: https://bitbucket.org/backbase/lp-module-ng-template/src.

We will update and release a fix for this in the nightly builds soon.

In the short term you can clone the template locally and configure the cli to reference the local template.

See the setup doc for this: https://github.com/Backbase/bb-cli/blob/nightly/docs/generate.md

Hope this helps

**Comment by KarunaL** [comment]
Thanks craig !!

**Comment by igord** [comment]
Fixed in latest nightly version.
