### ISSUE TITLE
Command line not working on Mac machine

### ISSUE THREAD

**Issue by Sahnil** [Backbase/bb-cli#113]
I am getting "error	spawn E2BIG" on all commands executed from bb

![screen shot 2015-12-10 at 2 55 52 pm](https://cloud.githubusercontent.com/assets/330486/11711681/37e82c52-9f4e-11e5-9eb3-69166829ae6c.png)

Not able to generate, import or export

I am using Mac OS X 10.11.1 (15B42)

![screen shot 2015-12-10 at 2 59 43 pm](https://cloud.githubusercontent.com/assets/330486/11711761/b0f9742a-9f4e-11e5-87e1-da7d2f09a4be.png)

**Comment by Sahnil** [comment]
Thanks in Advance!!

**Comment by igord** [comment]
This is fixed, in nightly version for sure. npm install -g bb-cli@nightly
