### ISSUE TITLE
bb import-item -l option is misleading to new users and customers

### ISSUE THREAD

**Issue by santam85** [Backbase/bb-cli#151]
On trainings, users expect the -l option to import every item immediately, without setting up watches.
They expect to have that function triggered by -lW, or -lWi if an initial import is desidered.

**Comment by karanarora** [comment]
@bartveenstra What is the bb-cli version that we can use to run bb import-item -l and be able to import all widgets for the very first time ?

**Comment by santam85** [comment]
v0.3.0
