### ISSUE TITLE
Update user's data for a given environment

### ISSUE THREAD

**Issue by fer** [Backbase/bb-cli#152]
Customers normally don't use CXP Manager on staging or production environments.

We need a method to change user's paswords for a given environment without the need to jump into the db and change values manually.

**Comment by craigwalkeruk** [comment]
I don't think I've seen a use case that we have users defined in cxp manager. Its normal that we integrate with a third party security provide SSO and LDAP. etc

We should probably close this ticket?

**Comment by torrespro** [comment]
Metrobank Commercial is using the CXP users directly. There's no need to change the users/password via DB, we used the REST API: https://my.backbase.com/docs/product-documentation/documentation/portal/5.6.1/rest_portalservices_user.html#/list

**Comment by craigwalkeruk** [comment]
Hi fer, this is one we should look at in the archetype not here.
