### ISSUE TITLE
Unable to install bb-cli

### ISSUE THREAD

**Issue by SnehaLPai** [Backbase/bb-cli#171]
I get the following error on trying to install bb-cli

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\snehap932\AppData\Roaming\npm\node_modules\bb-cli\node_modules\@bb-cli\bb-generate\node_modules\uc.micro' -> 'C:\Users\snehap932\AppData\Roaming\npm\node_modules\bb-cli\node_modules\@bb-cli\bb-generate\node_modules\.uc.micro.DELETE'

Is there any way out?

**Comment by igord** [comment]
Looks like a permission issue?
But the package that you are trying to install is @bb-cli/bb-package and that is different than bb-cli which this repo refers to.
For help with @bb-cli tools, please contact Backbase support
