### ISSUE TITLE
Add new widgets to link map

### ISSUE THREAD

**Issue by sorohan** [Backbase/bb-cli#42]
bb link needs to be updated for new banking widgets:
widget-transactions-search
widget-transactions-list
widget-transactions-chart-donut
widget-transactions-overview

**Comment by operatino** [comment]
Do we really want to support this map on cli tool level? It will require quite a lot of updates. Maybe we will just create a bit more verbose configuration instead?

Or shall we move this collection to other repo?

cc @igord

**Comment by sorohan** [comment]
Yeah. I agree. But I've instructed the guys not to put any more widgets in bundles like banking, universal, etc. So this is just a map of all the widgets that aren't in flat structure. All new widgets will be in flat structure so this shouldn't need to be updated.

**Comment by igord** [comment]
I added first 3, 4th was already there. (forget mentioning issue in commit msg)
