### ISSUE TITLE
Add support for generating templates from remote url

### ISSUE THREAD

**Issue by operatino** [Backbase/bb-cli#44]
Until we will introduce some mechanism for creating template bundles (or just switch to yeoman), it will be useful to add remote templates support for current `bb generate`.

This will be very handy for training and syncing with other teams:

```
bb generate ssh://git@stash.backbase.com:7999/lp/widget-ng-template.git
```

**Comment by operatino** [comment]
@GuilhermeMedeiros @dragosh

**Comment by stephanepericat** [comment]
I agree, it would avoid having to hardcode the lp12 templates in the cli if we could get the remote versions. Problem lies with partners and customers, who will not be able to access stash...

**Comment by craigwalkeruk** [comment]
We can put this on to github, along with all templates in bb generate

**Comment by stephanepericat** [comment]
It should remain an option though, so that you can still scaffold widgets using "local" templates if you have no internet or github is down...

**Comment by igord** [comment]
nightly is downloading them from bitbucket
