### ISSUE TITLE
`get` method is not working properly in `bb rest`

### ISSUE THREAD

**Issue by operatino** [Backbase/bb-cli#48]
Current behaviour:
* On `get` call like `bb rest -t portalCatalog -p dashboard`, stdout is only the status code

![image](http://d.pr/i/18O1Q+)

* If `-s` flag set, the XML output is broken

```
&lt;?xml version="1.0" encoding="UTF-8" standalone="yes"?>&lt;catalog totalSize="0"/>
```

Expected behaviour:

* On get, it should output the contents of the request
* Saving response to file, escaped XML

**Comment by igord** [comment]
fixed in 0.3.0
