### ISSUE TITLE
Add zip upload support to `bb sync`

### ISSUE THREAD

**Issue by operatino** [Backbase/bb-cli#49]
As in CXP 5.6 it's possible to store widgets in content services, we need a nice automated way of syncing changes of local widget to remote portal.

We should add some configuration flag, that instead of uploading just model, will zip widget into package and submit it into proper CXP API.

This should also be available with `watch`.

**Comment by igord** [comment]
Robert, you can use bb export to export widget only and bb import to import it. Did you try that?

**Comment by operatino** [comment]
It's using `/import/package` API.

**Comment by igord** [comment]
Implemented as import-item command
