### ISSUE TITLE
Handle mvn-credentials PR

### ISSUE THREAD

**Issue by operatino** [Backbase/bb-cli#52]
After @mistermark will accept [latest PR](https://github.com/mistermark/mvn-credentials/pull/3) to `mvn-credentials` and release updated version, we should point this dependency to original NPM package.

Currently it's pointing to my fork https://github.com/operatino/mvn-credentials.

**Comment by mistermark** [comment]
Pull request has been merge back into the repo and updated on NPM repository.
Dependency can be pointed back to original repo.
