### ISSUE TITLE
Error running 'npm link' on bb-cli nightly branch in Windows:

### ISSUE THREAD

**Issue by stephanepericat** [Backbase/bb-cli#55]
If we checkout the bb-cli repo, switch to the **nightly** branch, and run `npm link`, we get the following error on Windows: [https://gist.github.com/stephanepericat/81eef280b60d16e24e14](https://gist.github.com/stephanepericat/81eef280b60d16e24e14)

**Comment by igord** [comment]
can not reproduce :santa:
