### ISSUE TITLE
Command help should display option default

### ISSUE THREAD

**Issue by mistermark** [Backbase/bb-cli#73]
On the `-h` (help) option for every command it should display what the default value is of each option. Not all options are mandatory, but the mandatory ones have a default value. It would help to indicate what the default value of each option would be.

Example from command `jekyll --help`:

````
$ jekyll --help
jekyll 2.5.3 -- Jekyll is a blog-aware, static site generator in Ruby

Usage:

  jekyll <subcommand> [options]

Options:
        -s, --source [DIR]  Source directory (defaults to ./)
        -d, --destination [DIR]  Destination directory (defaults to ./_site)
            --safe         Safe mode (defaults to false)
        -p, --plugins PLUGINS_DIR1[,PLUGINS_DIR2[,...]]  Plugins directory (defaults to ./_plugins)
            --layouts DIR  Layouts directory (defaults to ./_layouts)
        -h, --help         Show this message
        -v, --version      Print the name and version
        -t, --trace        Show the full backtrace when an error occurs
````

**Comment by igord** [comment]
@mistermark I do that for all of my commands. Which commands don't include default values?

**Comment by mistermark** [comment]
I see that most of the commands have the default value specified, but it just didn't show for me on my terminal. Because I'm using a custom color scheme on my terminal some text is just not showing up.

Maybe an idea to improve the visibility of the text instead?

Normal text display:
![screen shot 2015-09-24 at 11 38 35](https://cloud.githubusercontent.com/assets/960311/10070131/dd0922d4-62b0-11e5-9af6-82d3bb476b0b.png)

Selected text:
![screen shot 2015-09-24 at 11 39 28](https://cloud.githubusercontent.com/assets/960311/10070147/f0e6671c-62b0-11e5-8a47-18187db9b022.png)

**Comment by igord** [comment]
I suggest you to tweak your color scheme as gray is commonly used and it is one of the few options that chalk library provides. And chalk is one of the most popular node libraries. https://www.npmjs.com/package/chalk
