### ISSUE TITLE
bb generate lp12-module is not creating model.xml

### ISSUE THREAD

**Issue by KarunaL** [Backbase/bb-cli#79]
I am using bb-cli#0.2.2, i tried to generate a module and i succeed it. But i couldn't find model.xml. So when i try to import-item, it says no model.xml found. Should i need to create model.xml manually ? bb-cli will not do it for me as like it did for widget generation ?

**Comment by GuilhermeMedeiros** [comment]
You can use `bb import-item -a`

**Comment by KarunaL** [comment]
Yes i tried this, but if i am supposed to watch the module changes with <code>bb import-item -w</code>. To all my changes, cmd is prompting as
<code>model.xml is not found.</code>
<code>? Auto submit one? Yes</code>

Is it possible to import without prompt for every changes ?

**Comment by igord** [comment]
Yes, just create model.xml and keep it in your repo :) You can see what is exactly autocreated by looking at model.xml of any LP module
