### ISSUE TITLE
-H and -P not working

### ISSUE THREAD

**Issue by salvitas** [Backbase/bb-cli#80]
while using the command import-item if i specify the host through the -H myhost.com it takes by default localhost so i have to always use --host!

**Comment by salvitas** [comment]
all commands that uses rest, should share the same options object.
For example options object in import-item.js is:
options: {
        target: {type: 'string', alias: 't', default: './'},
        watch: {type: 'boolean', alias: 'w'},
        collection: {type: 'boolean', alias: 'l'},
        'init-import': {type: 'boolean', alias: 'i'},
        auto: {type: 'boolean', alias: 'a'},
        name: {type: 'string', alias: 'n'},
        version: {type: 'string', alias: 'v'},
        verbose: {type: 'boolean'},
    },

so it does not specify the host alias as its done in rest.js
options: {
        scheme: {type: 'string', alias: 'S'},
        host: {type: 'string', alias: 'H'},
        port: {type: 'string', alias: 'P'},
        context: {type: 'string', alias: 'c'},
        username: {type: 'string', alias: 'u'},
        password: {type: 'string', alias: 'w'},
        portal: {type: 'string', alias: 'p'},
        target: {type: 'string', alias: 't', default: 'server'},
        'target-arg': {type: 'string', alias: 'T'},
        method: {type: 'string', alias: 'm', default: 'get'},
        file: {type: 'string', alias: 'f'},
        rights: {type: 'boolean', alias: 'r'},
        tag: {type: 'boolean', alias: 'g'},
        query: {type: 'string', alias: 'q'},
        'empty-cache': {type: 'boolean', alias: 'x'},
        verbose: {type: 'boolean', alias: 'v'},
        json: {type: 'boolean', alias: 'j'},
        save: {type: 'string', alias: 's'},
        info: {type: 'boolean', alias: 'i'}
    },

**Comment by igord** [comment]
salva, they do. Look at lib/config getCommon method...

**Comment by salvitas** [comment]
I had a look, but the problem is the aliases where not in impot-collection.js and import-item.js

**Comment by igord** [comment]
@salvitas can  you create PR on nightly?
