### ISSUE TITLE
Add support for custom or multiple .bbrc files

### ISSUE THREAD

**Issue by mistermark** [Backbase/bb-cli#86]
When executing some commands it's easy to have the .bbrc file in place and have all server configuration settings in place. For pushing to multiple environments this could be an inconvenience as the settings are pre-configured.

Adding support for multiple .bbrc files could solve this problem. Either by allowing a command to point to a certain .bbrc file would be a solution. Eg.: `bb sync -f catalog-widget.xml --config .bbrc-dev`.

Or to have a setting in a master .bbrc in the root of the project to point to certain environment configuration could also solve this problem:
````
{
    "dev": {
        "scheme": "https",
        "host": "dev.server.com",
        "port": "9834",
        "context": "cxp-manager/",
        "username": "admin",
        "password": "sup3rS3cr37s4uc3",
        "portal": "remote-portal"
    },
    "local": {
        "scheme": "http",
        "host": "localhost",
        "port": "7777",
        "context": "portalserver/",
        "username": "admin",
        "password": "admin",
        "portal": "local-portal"
    }
}
````

**Comment by GuilhermeMedeiros** [comment]
Good point

**Comment by dmitrisweb** [comment]
Merged to the nightly branch https://github.com/Backbase/bb-cli/pull/137
