### ISSUE TITLE
Remove auto-updater

### ISSUE THREAD

**Issue by sorohan** [Backbase/bb-cli#98]
Myself and a few others have experienced blocking problems with the auto-updater. It will periodically just throw some E2BIG error and nothing in the CLI will work.

I don't think the CLI should auto-update anyway.

**Comment by mistermark** [comment]
I agree to not have the auto-updating taking place. I'd suggest to only display a message if a newer version is available by comparing the current and latest version number.

**Comment by igord** [comment]
@mistermark That is exactly how it is working, just showing information that new version is available. The same library is used by bower.

@sorohan E2BIG means that argument list is too long. Are you sure that autoupdater was causing it?

I am ok to remove it as I would like to see much less dependencies in bb-cli and autoupdater is not really important.

**Comment by sorohan** [comment]
Actually, it could be from the update-notifier. I can't seem to be able to replicate the problem so I can't tell for sure, but I think it's to do with the 'spawn' command, which both the notifier, and the updater both use.

Anyway I think it's a good idea to remove the auto-updating.

**Comment by mistermark** [comment]
Is this issue resolved?

**Comment by sorohan** [comment]
I think it's merged into nightly - not released yet.
